"use client";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import InitUser from "../components/InitUser";
import { RecoilRoot } from "recoil";
import { Toaster } from "@/components/ui/toaster";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <RecoilRoot>
            <Navbar />
            <InitUser />
            {children}
            <Toaster />
          </RecoilRoot>
        </ThemeProvider>
      </body>
    </html>
  );
}
